#!/bin/sh
cd `dirname $0`
../src/joint_virtual_mimo_and_data_gathering_for_wireless_sensor_networks -n .:../src $*
# for shared lib, use: opp_run -l ../src/joint_virtual_mimo_and_data_gathering_for_wireless_sensor_networks -n .:../src $*
